### ISSUE TITLE
Computing time Triangles

### ISSUE THREAD

**Issue by fravij99** [matteopicciolini/ray_tracing#19]
I opened this issue cause of the computational time spent to generate shapes using TriangleMesh. 
I tried to measure computing time generating a simple scene with sky, ground and the solid made by triangle's meshing, with no antialiasing and 10 rays per pixel. I built a graph of the time used in terms of the number of vertices passed by command line:

![computing_time](https://github.com/matteopicciolini/ray_tracing/assets/116730685/bd1d529a-2ead-4aaa-9c98-7ce2903abfd2)

We need a method to speed up the code. One soolution could be parallelize the Triangle and TriangleMes classes to be more efficient. Another way could be using a simple shape like a sphere to make a fast check for the rayInterception before calculating all the normals of the triangles.

**Comment by fravij99** [comment]
I implemented successfully the AABB method to decrease computing time. 
This method consists in generating a box contsaining the whole shape and doing a fast check before the rayInterception calculus: if the intersection between ray and box is null, the method return null. 

The computing time really decrease with this method adn the comparison with the previous graph is the following one:

![computing_time](https://github.com/matteopicciolini/ray_tracing/assets/116730685/1ea9aac9-c8d0-41b4-9cea-c3a41ae5fc61)

**Comment by fravij99** [comment]
Both graphs doesen't have error bars because I had no time to cycle the rendering enough times to have a significative variance of data.

**Comment by matteopicciolini** [comment]
Great! In which commit did you fix this issue? Can you provide a reference?

**Comment by fravij99** [comment]
I had no time to parallelize the TriangleMesh class, so this issue will be presented to te future users. It could be intresting also implement the KD tree method.
